import {
  APPROVED_STATUS,
  DRAFT_STATUS,
  PAID_STATUS,
  PROCESSING_STATUS,
  REJECTED_BY_APPROVER_STATUS,
  REJECTED_BY_CONTROLLER_STATUS,
  REJECTED_STATUS,
  REQUIRES_CHANGES_STATUS,
  SUBMITTED_BY_APPROVER_STATUS,
  SUBMITTED_STATUS,
  VOIDED_STATUS,
} from '../../domain/transfer-request/constants'

export const statusFilterMapping = {
  [APPROVED_STATUS]: [APPROVED_STATUS],
  [SUBMITTED_STATUS]: [SUBMITTED_STATUS, SUBMITTED_BY_APPROVER_STATUS],
  [REJECTED_STATUS]: [REJECTED_BY_APPROVER_STATUS, REJECTED_BY_CONTROLLER_STATUS],
  [VOIDED_STATUS]: [VOIDED_STATUS],
  [PROCESSING_STATUS]: [PROCESSING_STATUS],
  [REQUIRES_CHANGES_STATUS]: [REQUIRES_CHANGES_STATUS],
  [PAID_STATUS]: [PAID_STATUS],
  [DRAFT_STATUS]: [DRAFT_STATUS],
}

export type StatusFilterOption = keyof typeof statusFilterMapping

export const statusFilterOptions = Object.keys(statusFilterMapping) as Array<StatusFilterOption>

export const statusFilterLabel = {
  [APPROVED_STATUS]: 'Approved',
  [SUBMITTED_STATUS]: 'Submitted',
  [REJECTED_STATUS]: 'Rejected',
  [VOIDED_STATUS]: 'Voided',
  [PROCESSING_STATUS]: 'Processing',
  [REQUIRES_CHANGES_STATUS]: 'Requires Change',
  [PAID_STATUS]: 'Paid',
  [DRAFT_STATUS]: 'Draft',
}
