version: '3'
services:
  db_local:
    image: postgres:12
    container_name: emissary
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: my_super_secret_pw
