version: '3'
services:
  db:
    image: postgres:12
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: my_super_secret_pw
      POSTGRES_DB: filpass
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
