blank_issues_enabled: false
contact_links:
  - name: Need additional help?
    url: https://filecoinproject.slack.com/
    about: Post your need in the emissary-help channel, and someone will get back to you as soon as possible.
