export const PROGRAM_TYPE_INTERNAL = 'INTERNAL'
export const PROGRAM_TYPE_EXTERNAL = 'EXTERNAL'

export const ACTIVE_STATUS = 'ACTIVE'
export const ARCHIVED_STATUS = 'ARCHIVED'

export const REQUEST_TOKEN = 'TOKEN'