name: Deploy Production

on:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/**'
      - 'go-api/**'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

env:
  EB_ENV: crypto-ops-production
  APP_URL: https://pl.coinemissary.com
  NEXT_PUBLIC_APP_URL: https://pl.coinemissary.com
  NODE_ENV: production
  SENTRY_ORG: protocol-labs-zx
  SENTRY_PROJECT: protocol-labs-zx
  ENV_NAME: production
  GO_LANG_API: https://f5h7p47vvg.execute-api.us-east-2.amazonaws.com/production/lotus-client

jobs:
  deploy-app:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node-version: [14.19.0]
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2
      - name: Set env
        run: aws secretsmanager get-secret-value --secret-id $EB_ENV | jq -r '.SecretString' | jq -r 'to_entries | .[] | "\(.key)=\(.value)"' >> $GITHUB_ENV
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install AWS EB CLI
        run: |
          sudo apt-get install build-essential zlib1g-dev libssl-dev libncurses-dev libffi-dev libsqlite3-dev libreadline-dev libbz2-dev
          python3 -m pip install --user pipx
          python3 -m pipx ensurepath
          pipx install git+https://github.com/pypa/virtualenv.git#e2833afe407ea8a9b8abd79befd4339f7c1c873b
          git clone https://github.com/aws/aws-elastic-beanstalk-cli-setup.git
          python ./aws-elastic-beanstalk-cli-setup/scripts/ebcli_installer.py
          echo 'export PATH="/home/runner/.ebcli-virtual-env/executables:$PATH"' >> ~/.bash_profile && source ~/.bash_profile
      - name: Install dependencies
        run: npm install
        env:
          NODE_ENV: development
      - name: Run build
        run: npx prisma generate && npm run build
      - name: EB deploy
        run: |
          source ~/.bash_profile
          eb deploy ${{ env.EB_ENV }} -nh
