name: Deploy Development Lotus Client

on:
  push:
    branches:
      - development
    paths:
      - 'go-api/**'
  workflow_dispatch:

jobs:
  deploy-lotus-client:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node-version: [14.x]
    defaults:
      run:
        working-directory: go-api
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - uses: actions/setup-go@v3
        with:
          go-version: '1.18.4'
      - run: npm i -g serverless
      - run: make deploy stage=development
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
